# Maximum height a player can reach before being set on fire
max-height: 256

# The duration for which a player will be set on fire
fire-duration: 5

# Message to be sent to player
fire-message: "You flew too close to the sun!"

# Whether the message should be displayed or not
display-message: true

# The permission that allows a player to bypass the height limit and avoid being set on fire
bypass-permission: "icarus.bypass"